### ISSUE TITLE
Permissions issue

### ISSUE THREAD

**Issue by dmromanov** [insanio/bitrix-env-vagrant#1]
Vagrant 1.7.2, Bitrix Env. 5.1.2

Fresh install (provision) finishes successfuly, but Bitrix fails to run.

In httpd logs:

```
[Thu Apr 02 10:53:06 2015] [crit] [client 10.0.2.2] (13)Permission denied: /home/bitrix/www/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable
```

**Comment by nzy** [comment]
Я работал с этой строчкой и без нее.

Во всех новых проектах все работает без этих инструкций.

**Comment by nzy** [comment]
Проблема в том, что при первом запуске и попытке смонтировать папку с правами пользователя bitrix, возникает ошибка. Так как пользователя bitrix еще нет в системе. Он создается в provision'е bitrix-env.sh после mount'а.

**Comment by brave44** [comment]
Нужно поправить Vagranfile, там монтировать можно так: config.vm.synced_folder ".", "/home/bitrix/www", без указания юзера.

**Comment by nzy** [comment]
Мы так и монтируем, но говорят, что бывают случаи, когда это необходимо.

Нужно больше информации. Так ли это необходимо.

Если есть необходимость, можно попробовать изменить пользователя ssh с vagrant (по-умолчанию) на root, тогда mount будет проходить под root'ом.

**Comment by nzy** [comment]
Информация по теме: https://github.com/mitchellh/vagrant/issues/936
