### ISSUE TITLE
Права на папку /home/bitrix/

### ISSUE THREAD

**Issue by egorzot** [insanio/bitrix-env-vagrant#11]
Константин, добрый день!
Когда установлено окружение, группа и владелец папки /home/bitrix/ root, хотя php и mysql работают от пользователя bitrix, поэтому они не могут писать в /home/bitrix/www/.
Было бы вообще шикарно (имхо) если бы в папке /home/bitrix/www/ после установки веб окружения находился файлик bitrixsetup.php.
Спасибо за решение.

**Comment by nzy** [comment]
Добрый день.
1. Поправил права.
2. Добавил скачивание bitrixsetup.php.
