### ISSUE TITLE
Sendfile should be disabled by default in nginx and apache

### ISSUE THREAD

**Issue by dmromanov** [insanio/bitrix-env-vagrant#3]
https://docs.vagrantup.com/v2/synced-folders/virtualbox.html

**Comment by nzy** [comment]
Не вижу, что отсутствие этих инструкций как-то мешают работе.

**Comment by dmromanov** [comment]
@insanio 
100% проявляется на хостах Linux с провайдером VirtualBox.

Спасибо.
