### ISSUE TITLE
Проблема с загрузкой образа

### ISSUE THREAD

**Issue by StenHigh** [insanio/bitrix-env-vagrant#7]
При инициализации vagrant выдает ошибку:
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:
vm:
- The box 'chef/centos-6.5' could not be found.
  Я так понимаю что не может найти образ centos-6.5, подскажите пожалуйста как вы решили эту проблему.

**Comment by nzy** [comment]
chef/centos-6.5 - это образ из репозитория vagrant'a. Так называемый vagrant box. 

Подробнее тут:
https://docs.vagrantup.com/v2/boxes.html, https://docs.vagrantup.com/v2/vagrantfile/machine_settings.html

Попробуйте выполнить команду: vagrant init chef/centos-6.5

**Comment by StenHigh** [comment]
Проблема оказалась в том что у меня была старая версия vagrant. После обновления версии все заработало. Спасибо за ваш bitrix-env-vagrant.
